#ifndef FASTERRCNN_GLOBAL_H
#define FASTERRCNN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FASTERRCNN_LIBRARY)
#  define FASTERRCNNSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FASTERRCNNSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FASTERRCNN_GLOBAL_H
